[project]
name = "aon-mcp-server"
version = "0.1.0"
description = ""
authors = [
    {name = "myeonggil",email = "echosoul1994@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "yfinance (>=0.2.61,<0.3.0)",
    "fastmcp (>=2.7.1,<3.0.0)",
    "fast-agent-mcp (>=0.2.30,<0.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
